name: Java Maven CI with SonarQube

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]  # or self-hosted

    steps:
      # Checkout
      - name: Checkout source
        uses: actions/checkout@v4

      # Java 8 setup (matches your Maven 3.6 + Java 8 projects)
      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Force JAVA_HOME
        run: |
          echo "JAVA_HOME=${{ steps.setup-java.outputs.path }}" >> $GITHUB_ENV
          echo "${{ steps.setup-java.outputs.path }}/bin" >> $GITHUB_PATH

      - name: Install Maven 3.9.9
        run: |
          wget -q https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
          tar -xzf apache-maven-3.9.9-bin.tar.gz
          echo "$PWD/apache-maven-3.9.9/bin" >> $GITHUB_PATH

      # Verify tools
      - name: Verify versions
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          mvn -version

      # Build & Unit Test
      - name: Build with Maven
        run: mvn -B clean verify -Denforcer.skip=true

     # - name: Build + Sonar
      #  run: |
      #    mvn -B clean verify sonar:sonar \
      #      -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
      #      -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
            -Dsonar.projectName=${{ secrets.PROJECT_NAME }}
            -Dsonar.sources=src
            -Dsonar.java.binaries=target

      # Upload JAR (optional)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar
